CREATE TABLE HOME_TRANSIT
(
ID INT NOT NULL AUTO_INCREMENT,
CONTACT_NAME VARCHAR(64),
MAIL VARCHAR(32),
PHONE VARCHAR(24),
USER_ACCOUNT_ID INT,
DESCRIPTION VARCHAR(1500),
LATITUDE FLOAT(10,6),
LONGITUDE FLOAT(10,6),
HAS_MOVILITY VARCHAR(64),
PRIMARY KEY (ID),
FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID)

);






CREATE TABLE TRANSIT_TYPE
(
ID INT NOT NULL AUTO_INCREMENT,
HOME_TRANSIT_ID INT,
ANIMAL_TYPE VARCHAR(32),
ANIMAL_AGE VARCHAR(64),
ANIMAL_BREED VARCHAR (32),
DESCRIPTION VARCHAR(1500),
PRIMARY KEY (ID)

);

CREATE INDEX IDX_ANIMAL_AGE ON  TRANSIT_TYPE(ANIMAL_AGE);

CREATE INDEX IDX_ANIMAL_TYPE ON  TRANSIT_TYPE(ANIMAL_TYPE);