CREATE TABLE PET
(
ID INT NOT NULL AUTO_INCREMENT,
ALIAS VARCHAR(64) NOT NULL,
ANIMAL_TYPE VARCHAR(32) NOT NULL,
USER_ACCOUNT_ID INT,
PHOTO BLOB,
PRIMARY KEY (ID),
FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID)
);