CREATE TABLE USER_ACCOUNT
(
ID INT NOT NULL AUTO_INCREMENT,
FULLNAME  VARCHAR(64) NOT NULL,
USERNAME VARCHAR(32) UNIQUE NOT NULL,
PASS_TOKEN VARCHAR(64) NOT NULL,
MAIL VARCHAR(32) UNIQUE NOT NULL,
PHONE VARCHAR(24),
PHOTO BLOB,
VALIDATED CHAR,
BIOGRAPHY VARCHAR(140),
LOCATION VARCHAR (55),
ACCESS_TOKEN VARCHAR(64),
PRIMARY KEY (ID),
UNIQUE KEY  (MAIL,USERNAME)
);

