CREATE TABLE PUBLICATION
(
ID INT NOT NULL AUTO_INCREMENT,
USER_ACCOUNT_ID INT,
PUBLICATION_STATUS VARCHAR(50),
PUBLICATION_TYPE VARCHAR(50),
TITLE VARCHAR(64) NOT NULL,
ANIMAL_TYPE VARCHAR(32),
ANIMAL_BREED VARCHAR (32),
DESCRIPTION VARCHAR(1500),
STRING_LOCATION VARCHAR(200),
COLOR VARCHAR(32),
SIZE VARCHAR(32),
GENDER VARCHAR(32),
LATITUDE FLOAT(10,6),
LONGITUDE FLOAT(10,6),
PET_NAME VARCHAR(64),
CONTACT_NAME VARCHAR(64),
PHONE VARCHAR(32),
EMAIL VARCHAR(32),
IMAGE_ID INT,
STATUS VARCHAR(32),
PRIMARY KEY (ID),
FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)

);

CREATE INDEX IDX_PUBLICATION_TYPE ON  PUBLICATION(PUBLICATION_TYPE);

CREATE INDEX IDX_ANIMAL_TYPE ON  PUBLICATION(ANIMAL_TYPE);

CREATE INDEX IDX_LATITUDE ON  PUBLICATION(LATITUDE);
CREATE INDEX IDX_LONGITUDE ON  PUBLICATION(LONGITUDE);